# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mattcfish
tagline:          ''
description:      'a busy dad learns investing'
url:              https://mattcfish.com
baseurl:          /

author:
  name:           'matt fisher'
  url:            https://twitter.com/mattcfish

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
