# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mattcfish
tagline:          ''
description:      'busy dad learns investing'
url:              https://mattcfish.com
baseurl:          /

author:
  name:           'matt fisher'
  url:            https://twitter.com/mattcfish

paginate:         5

# Custom vars
version:          1.0.0
