# Setup
title:               matt.c.fisher
tagline:             ''
description:         'Reomote work for busy people'
url:                 http://mattcfish.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matt Fisher
  url:               https://twitter.com/mattcfish

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
